name: ForceSpawn
version: ${project.version}
main: com.forcespawn.ForceSpawnPlugin
api-version: '${plugin.api.version}'
author: ForceSpawn
description: Forces all players to spawn in The End and disables the Overworld.
load: STARTUP
